-- MySQL Script generated by MySQL Workbench
-- 09/24/14 17:34:48
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema safdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `safdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `safdb` ;

-- -----------------------------------------------------
-- Table `safdb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `safdb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `codigo` INT NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`Perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`Perfil` ;

CREATE TABLE IF NOT EXISTS `safdb`.`Perfil` (
  `idPerfil` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`PerfilUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`PerfilUsuario` ;

CREATE TABLE IF NOT EXISTS `safdb`.`PerfilUsuario` (
  `idUsuario` INT NOT NULL,
  `idPerfil` INT NOT NULL,
  INDEX `fk_PerfilUsuario_Usuario_idx` (`idUsuario` ASC),
  INDEX `fk_PerfilUsuario_Perfil1_idx` (`idPerfil` ASC),
  PRIMARY KEY (`idUsuario`, `idPerfil`),
  CONSTRAINT `fk_PerfilUsuario_Usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `safdb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PerfilUsuario_Perfil1`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `safdb`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`Funcionalidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`Funcionalidad` ;

CREATE TABLE IF NOT EXISTS `safdb`.`Funcionalidad` (
  `idFuncionalidad` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFuncionalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`FuncionalidadPerfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`FuncionalidadPerfil` ;

CREATE TABLE IF NOT EXISTS `safdb`.`FuncionalidadPerfil` (
  `idPerfil` INT NOT NULL,
  `idFuncionalidad` INT NOT NULL,
  INDEX `fk_FuncionalidadPerfil_Perfil1_idx` (`idPerfil` ASC),
  INDEX `fk_FuncionalidadPerfil_Funcionalidad1_idx` (`idFuncionalidad` ASC),
  PRIMARY KEY (`idPerfil`, `idFuncionalidad`),
  CONSTRAINT `fk_FuncionalidadPerfil_Perfil1`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `safdb`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FuncionalidadPerfil_Funcionalidad1`
    FOREIGN KEY (`idFuncionalidad`)
    REFERENCES `safdb`.`Funcionalidad` (`idFuncionalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `safdb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(15) NOT NULL,
  `apellidos` VARCHAR(15) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(15) NULL,
  `email` VARCHAR(30) NULL,
  `cedula` INT NULL,
  `razon_social` VARCHAR(45) NULL,
  `rut` INT NULL,
  `descuento` DECIMAL(5,2) NULL,
  `fcreacion` DATETIME NOT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`CuentaCliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`CuentaCliente` ;

CREATE TABLE IF NOT EXISTS `safdb`.`CuentaCliente` (
  `idCuenta` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `saldo` DECIMAL(10,2) NOT NULL,
  `tope` DECIMAL(10,2) NOT NULL,
  `fcreacion` DATETIME NOT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idCuenta`),
  INDEX `fk_CuentaCliente_Cliente1_idx` (`idCliente` ASC),
  CONSTRAINT `fk_CuentaCliente_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `safdb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`Proveedor` ;

CREATE TABLE IF NOT EXISTS `safdb`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NULL,
  `web` VARCHAR(45) NULL,
  `habilitado` BIT NOT NULL,
  `fcreacion` DATETIME NOT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`TipoIVA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`TipoIVA` ;

CREATE TABLE IF NOT EXISTS `safdb`.`TipoIVA` (
  `idTipoIVA` INT NOT NULL,
  `descripcion` VARCHAR(10) NOT NULL,
  `porcentaje` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`idTipoIVA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`Producto` ;

CREATE TABLE IF NOT EXISTS `safdb`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `idTipoIVA` INT NOT NULL,
  `descripcion` VARCHAR(60) NOT NULL,
  `precioCompra` DECIMAL(10,2) NOT NULL,
  `precioVenta` DECIMAL(10,2) NOT NULL,
  `habilitado` TINYINT(1) NOT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_TipoIVA1_idx` (`idTipoIVA` ASC),
  CONSTRAINT `fk_Producto_TipoIVA1`
    FOREIGN KEY (`idTipoIVA`)
    REFERENCES `safdb`.`TipoIVA` (`idTipoIVA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`CodigoProducto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`CodigoProducto` ;

CREATE TABLE IF NOT EXISTS `safdb`.`CodigoProducto` (
  `idCodigoProducto` INT NOT NULL AUTO_INCREMENT,
  `idProducto` INT NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idCodigoProducto`, `idProducto`),
  INDEX `fk_CodigoProducto_Producto1_idx` (`idProducto` ASC),
  CONSTRAINT `fk_CodigoProducto_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `safdb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`ProductoProveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`ProductoProveedor` ;

CREATE TABLE IF NOT EXISTS `safdb`.`ProductoProveedor` (
  `idProducto` INT NOT NULL,
  `idProveedor` INT NOT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idProducto`, `idProveedor`),
  INDEX `fk_ProductoProveedor_Proveedor1_idx` (`idProveedor` ASC),
  CONSTRAINT `fk_ProductoProveedor_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `safdb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductoProveedor_Proveedor1`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `safdb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`AccionTerapeutica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`AccionTerapeutica` ;

CREATE TABLE IF NOT EXISTS `safdb`.`AccionTerapeutica` (
  `idAccionTerapeutica` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idAccionTerapeutica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`Presentacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`Presentacion` ;

CREATE TABLE IF NOT EXISTS `safdb`.`Presentacion` (
  `idPresentacion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idPresentacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`Laboratorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`Laboratorio` ;

CREATE TABLE IF NOT EXISTS `safdb`.`Laboratorio` (
  `idLaboratorio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `departamento` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idLaboratorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`Medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`Medicamento` ;

CREATE TABLE IF NOT EXISTS `safdb`.`Medicamento` (
  `idProducto` INT NOT NULL,
  `idPresentacion` INT NOT NULL,
  `idLaboratorio` INT NOT NULL,
  `requiereReceta` TINYINT(1) NOT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Medicamento_Presentacion1_idx` (`idPresentacion` ASC),
  INDEX `fk_Medicamento_Laboratorio1_idx` (`idLaboratorio` ASC),
  CONSTRAINT `fk_Medicamento_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `safdb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medicamento_Presentacion1`
    FOREIGN KEY (`idPresentacion`)
    REFERENCES `safdb`.`Presentacion` (`idPresentacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medicamento_Laboratorio1`
    FOREIGN KEY (`idLaboratorio`)
    REFERENCES `safdb`.`Laboratorio` (`idLaboratorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`AccionTerapeuticaMedicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`AccionTerapeuticaMedicamento` ;

CREATE TABLE IF NOT EXISTS `safdb`.`AccionTerapeuticaMedicamento` (
  `idAccionTerapeutica` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idAccionTerapeutica`, `idProducto`),
  INDEX `fk_AccionTerapeuticaProducto_AccionTerapeutica1_idx` (`idAccionTerapeutica` ASC),
  INDEX `fk_AccionTerapeuticaProducto_Medicamento1_idx` (`idProducto` ASC),
  CONSTRAINT `fk_AccionTerapeuticaProducto_AccionTerapeutica1`
    FOREIGN KEY (`idAccionTerapeutica`)
    REFERENCES `safdb`.`AccionTerapeutica` (`idAccionTerapeutica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AccionTerapeuticaProducto_Medicamento1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `safdb`.`Medicamento` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`Droga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`Droga` ;

CREATE TABLE IF NOT EXISTS `safdb`.`Droga` (
  `idDroga` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idDroga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`DrogaMedicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`DrogaMedicamento` ;

CREATE TABLE IF NOT EXISTS `safdb`.`DrogaMedicamento` (
  `idDroga` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idDroga`, `idProducto`),
  INDEX `fk_DrogaProducto_Droga1_idx` (`idDroga` ASC),
  INDEX `fk_DrogaProducto_Medicamento1_idx` (`idProducto` ASC),
  CONSTRAINT `fk_DrogaProducto_Droga1`
    FOREIGN KEY (`idDroga`)
    REFERENCES `safdb`.`Droga` (`idDroga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DrogaProducto_Medicamento1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `safdb`.`Medicamento` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`TipoOfertaDescuento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`TipoOfertaDescuento` ;

CREATE TABLE IF NOT EXISTS `safdb`.`TipoOfertaDescuento` (
  `idTipoOfertaDescuento` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idTipoOfertaDescuento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`OfertaDescuento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`OfertaDescuento` ;

CREATE TABLE IF NOT EXISTS `safdb`.`OfertaDescuento` (
  `idOfertaDescuento` INT NOT NULL AUTO_INCREMENT,
  `idTipoOfertaDescuento` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `cantBonif` INT NULL,
  `porcentBonif` DECIMAL(5,2) NULL,
  `montoBonif` DECIMAL(10,2) NULL,
  `cantMin` INT NULL,
  `montoMin` DECIMAL(10,2) NULL,
  `habilitado` TINYINT(1) NOT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idOfertaDescuento`),
  INDEX `fk_OfertaDescuento_TipoOfertaDescuento1_idx` (`idTipoOfertaDescuento` ASC),
  CONSTRAINT `fk_OfertaDescuento_TipoOfertaDescuento1`
    FOREIGN KEY (`idTipoOfertaDescuento`)
    REFERENCES `safdb`.`TipoOfertaDescuento` (`idTipoOfertaDescuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`Stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`Stock` ;

CREATE TABLE IF NOT EXISTS `safdb`.`Stock` (
  `idProducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idProducto`),
  CONSTRAINT `fk_Stock_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `safdb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`VencimientoStock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`VencimientoStock` ;

CREATE TABLE IF NOT EXISTS `safdb`.`VencimientoStock` (
  `idVencimientoStock` INT NOT NULL AUTO_INCREMENT,
  `idProducto` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idVencimientoStock`),
  INDEX `fk_VencimientoStock_Stock1_idx` (`idProducto` ASC),
  CONSTRAINT `fk_VencimientoStock_Stock1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `safdb`.`Stock` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`PagoCuentaCorriente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`PagoCuentaCorriente` ;

CREATE TABLE IF NOT EXISTS `safdb`.`PagoCuentaCorriente` (
  `idPagoCuentaCorriente` INT NOT NULL AUTO_INCREMENT,
  `idCuenta` INT NOT NULL,
  `monto` DECIMAL(10,2) NOT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idPagoCuentaCorriente`),
  INDEX `fk_PagoCuentaCorriente_CuentaCliente1_idx` (`idCuenta` ASC),
  CONSTRAINT `fk_PagoCuentaCorriente_CuentaCliente1`
    FOREIGN KEY (`idCuenta`)
    REFERENCES `safdb`.`CuentaCliente` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`TipoFactura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`TipoFactura` ;

CREATE TABLE IF NOT EXISTS `safdb`.`TipoFactura` (
  `idTipoFactura` TINYINT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoFactura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`Factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`Factura` ;

CREATE TABLE IF NOT EXISTS `safdb`.`Factura` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `idTipoFactura` TINYINT NOT NULL,
  `idCliente` INT NULL,
  `RUT` VARCHAR(45) NULL,
  `razonSocial` VARCHAR(45) NULL,
  `fecha` DATETIME NOT NULL,
  `descuento` DECIMAL(5,2) NOT NULL,
  `montoNetoTotal` DECIMAL(10,2) NOT NULL,
  `montoNetoGralIVA` DECIMAL(10,2) NOT NULL,
  `montoNetoGralIVAMin` DECIMAL(10,2) NOT NULL,
  `montoTotal` DECIMAL(10,2) NOT NULL,
  `montoTotalAPagar` DECIMAL(10,2) NOT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idFactura`, `idTipoFactura`),
  INDEX `fk_Factura_Cliente1_idx` (`idCliente` ASC),
  CONSTRAINT `fk_Factura_TipoFactura1`
    FOREIGN KEY (`idTipoFactura`)
    REFERENCES `safdb`.`TipoFactura` (`idTipoFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `safdb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`RenglonFactura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`RenglonFactura` ;

CREATE TABLE IF NOT EXISTS `safdb`.`RenglonFactura` (
  `idRenglonFactura` INT NOT NULL AUTO_INCREMENT,
  `idTipoFactura` TINYINT NOT NULL,
  `idFactura` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `conReceta` TINYINT(1) NOT NULL,
  `precioProducto` DECIMAL(10,2) NOT NULL,
  `precioVentaReal` DECIMAL(10,2) NOT NULL,
  `descDescripcion` VARCHAR(45) NULL,
  `descCantBonif` INT NULL,
  `descPorcentBonif` DECIMAL(5,2) NULL,
  `descMontoBonif` DECIMAL(10,2) NULL,
  `idTransaccion` BIGINT NULL,
  INDEX `fk_RenglonFactura_Factura1_idx` (`idTipoFactura` ASC, `idFactura` ASC),
  PRIMARY KEY (`idRenglonFactura`),
  CONSTRAINT `fk_RenglonFactura_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `safdb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RenglonFactura_Factura1`
    FOREIGN KEY (`idTipoFactura` , `idFactura`)
    REFERENCES `safdb`.`Factura` (`idTipoFactura` , `idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`TipoFormaPago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`TipoFormaPago` ;

CREATE TABLE IF NOT EXISTS `safdb`.`TipoFormaPago` (
  `idTipoFormaPago` TINYINT NOT NULL,
  `nombre` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idTipoFormaPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`FormaPagoFactura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`FormaPagoFactura` ;

CREATE TABLE IF NOT EXISTS `safdb`.`FormaPagoFactura` (
  `idFactura` INT NOT NULL,
  `idTipoFactura` TINYINT NOT NULL,
  `idTipoFormaPago` TINYINT NOT NULL,
  `nroTarjeta` INT NULL,
  `idCuenta` INT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idFactura`, `idTipoFactura`),
  INDEX `fk_FormaPagoFactura_Factura1_idx` (`idTipoFactura` ASC, `idFactura` ASC),
  INDEX `fk_FormaPagoFactura_CuentaCliente1_idx` (`idCuenta` ASC),
  CONSTRAINT `fk_FormaPagoFactura_TipoFormaPago1`
    FOREIGN KEY (`idTipoFormaPago`)
    REFERENCES `safdb`.`TipoFormaPago` (`idTipoFormaPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FormaPagoFactura_Factura1`
    FOREIGN KEY (`idTipoFactura` , `idFactura`)
    REFERENCES `safdb`.`Factura` (`idTipoFactura` , `idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FormaPagoFactura_CuentaCliente1`
    FOREIGN KEY (`idCuenta`)
    REFERENCES `safdb`.`CuentaCliente` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`Compra` ;

CREATE TABLE IF NOT EXISTS `safdb`.`Compra` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `tipo` INT NOT NULL,
  `fechaEmision` DATETIME NOT NULL,
  `vencimiento` DATETIME NOT NULL,
  `montoNetoGralIVA` DECIMAL(10,2) NOT NULL,
  `montoNetoGralIVABas` DECIMAL(10,2) NOT NULL,
  `montoNoFac` DECIMAL(10,2) NOT NULL,
  `montoNoGra` DECIMAL(10,2) NOT NULL,
  `montoRetIRAE` DECIMAL(10,2) NOT NULL,
  `montoRetIVA` DECIMAL(10,2) NOT NULL,
  `montoTotal` DECIMAL(10,2) NOT NULL,
  `montoTotalAPagar` DECIMAL(10,2) NOT NULL,
  `montoTribIVABas` DECIMAL(10,2) NOT NULL,
  `montoTribIVAMin` DECIMAL(10,2) NOT NULL,
  `ordenCompra` DECIMAL(10,2) NOT NULL,
  `totalIVABas` DECIMAL(10,2) NOT NULL,
  `totalIVAMin` DECIMAL(10,2) NOT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idCompra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`ProductoCompra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`ProductoCompra` ;

CREATE TABLE IF NOT EXISTS `safdb`.`ProductoCompra` (
  `idCompra` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `nroLinea` INT NULL,
  `cantidad` INT NULL,
  `idTransaccion` BIGINT NULL,
  PRIMARY KEY (`idCompra`, `idProducto`),
  INDEX `fk_ProductoCompra_Stock1_idx` (`idProducto` ASC),
  CONSTRAINT `fk_ProductoCompra_Compra1`
    FOREIGN KEY (`idCompra`)
    REFERENCES `safdb`.`Compra` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductoCompra_Stock1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `safdb`.`Stock` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`TransaccionUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`TransaccionUsuario` ;

CREATE TABLE IF NOT EXISTS `safdb`.`TransaccionUsuario` (
  `idTransaccion` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idFuncionalidad` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`idTransaccion`, `idUsuario`, `idFuncionalidad`),
  INDEX `fk_TransaccionUsuario_Usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_TransaccionUsuario_Funcionalidad1_idx` (`idFuncionalidad` ASC),
  CONSTRAINT `fk_TransaccionUsuario_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `safdb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TransaccionUsuario_Funcionalidad1`
    FOREIGN KEY (`idFuncionalidad`)
    REFERENCES `safdb`.`Funcionalidad` (`idFuncionalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`EnvioFactura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`EnvioFactura` ;

CREATE TABLE IF NOT EXISTS `safdb`.`EnvioFactura` (
  `idFactura` INT NOT NULL,
  `idUsuarioDelivery` INT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(15) NULL,
  `Observaciones` VARCHAR(60) NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_EnvioFactura_Usuario1_idx` (`idUsuarioDelivery` ASC),
  CONSTRAINT `fk_EnvioFactura_Factura1`
    FOREIGN KEY (`idFactura`)
    REFERENCES `safdb`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EnvioFactura_Usuario1`
    FOREIGN KEY (`idUsuarioDelivery`)
    REFERENCES `safdb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safdb`.`OfertaDescuentoProducto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `safdb`.`OfertaDescuentoProducto` ;

CREATE TABLE IF NOT EXISTS `safdb`.`OfertaDescuentoProducto` (
  `idOfertaDescuento` INT NOT NULL,
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`idOfertaDescuento`, `idProducto`),
  INDEX `fk_ProductoOfertaDescuento_Producto1_idx` (`idProducto` ASC),
  CONSTRAINT `fk_ProductoOfertaDescuento_OfertaDescuento1`
    FOREIGN KEY (`idOfertaDescuento`)
    REFERENCES `safdb`.`OfertaDescuento` (`idOfertaDescuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductoOfertaDescuento_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `safdb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE Producto AUTO_INCREMENT = 100000;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
